// This URL below can be replaced with any Virtual Background Image URL
export const vbgImageUrl = "./images/V_B_G.jpg";

// Obtain the following meetingInfo by creating a new meeting in the Webex Developer Portal
// Read through this API Reference to know more:
// https://developer.webex.com/docs/api/v1/meetings/create-a-meeting
// Once meeting is created, copy the whole response and paste it here.
// Note - Unless we have this information, this demo cannot join a meeting
export const meetingInfo = {}; // REQUIRED

// To get guestIssueAccessToken and guestEndpointUrl
// Update the following with the Guest Issuer Access Token through Service Apps
// Read more about it here: https://developer.webex.com/docs/sa-guest-management
// Note - Unless we have this token, this demo cannot join a meeting
export const guestIssuerAccessToken = ""; // OPTIONAL
export const guestEndpointUrl = ""; //OPTIONAL

//To get access token visit - https://developer.webex.com/docs/getting-started
export const personalAccessToken = "eyJhbGciOiJSUzI1NiJ9.eyJtYWNoaW5lX3R5cGUiOiJseXJhX3NwYWNlIiwiY2x1c3RlciI6IlBGODQiLCJwcml2YXRlIjoiZXlKamRIa2lPaUpLVjFRaUxDSmxibU1pT2lKQk1USTRRMEpETFVoVE1qVTJJaXdpWVd4bklqb2laR2x5SW4wLi5RdW11MnlXMzNpYWVhU2tZZmwwTlR3Lnd0Nkhsc0dxVm10R2JldW53QWlsWHVzZV85R01BX2JYbE1NZjRIWGVYSFZXR3JSeVNZTHUwMTdla2ZEUVVWeVQ3TXlfTDJza2l6ZFZLYW0zWlpaX2FicUpCTTlmb2g4aXUwRkl5RHFkaHhZb29xRXg3TEN4bzNZc0FRcjA4c2NzRlNkcjM4Q0plZ3lNZUlsNk1KcVp0X3dsdTBBQWZzVnpjVXB3Y2MxRlNac3d1SVY5RnJDR25BbWxGVFhoc2VjVGlDM2E3WUk4eFZUeEFyY2JFYno3VEs1aTJQZFpLTU5mdFVKTnBvQW9UZXNweU5tSmRrLUtqUHpzTU00X3pLMGRVUmZpSHltMEFGU0dTS0FjaDBQcFd3MW93UjZpVmFvd0lyQmFteXkzTmZZOVlwTWFSSDdsOUlkSzdhXzJWWU9NVUdJU0w1MVB6OVZsQTRhNC1TX29xdU95eVNvaVY1Z1B0WjN5OHFwOUUtWWJVUVFaWE1CdnJZZlhlcHFudUFfVlMxTXdEVnQtT1d5MGh4azllcV9FQlRjNWZVbmxvOXRtWFJxWS14d25oT2dYaTM3a3hMYXdJal9hQWFGSjBvai1BWlpyRnBmanhyZFBhWElPTTNTVUlQNFNTSjdHM2xvRi1ZRFRweWlkREEwbFZvd3ZwbkdDZThvUTBtTlVWRW5DZWNUS1pVM2RDSXYtY05IbFRrVUx1cUFSVmRLaG1nT3VvQUtJb2hlSlc3eVdpU2o1RmJiczl4cmNjbGJzMHNkR1pYMDB1dWw2NjN5bFF3dmJTUzh5bXpSY2Q1TDkzX3N4VExxbWMwZTFDb3c1RFFkeV93WHFhdG9JMG1ucVpOOG5DaHdsek8ySXB3TGxMWHJxUGJfV2UzODU1TFZkSkdjc2Y5TVF3LVlIR0JRZnZYVmZPaERscXIyQ3o1Y3E0eE00eUsxZE4wYk9Tb3Q4RjVpMk9xTDNPUS5nN2ZaZ1BZUzFuUWd5Nmo2WF9UZUt3IiwicmVmZXJlbmNlX2lkIjoiNTRjZGVhMDgtNTJhNC00ZTFhLWE0MWQtNjhjMjliNmVmOWM0IiwiaXNzIjoiaHR0cHM6Ly9pZGJyb2tlci53ZWJleC5jb20vaWRiIiwidG9rZW5fdHlwZSI6IkJlYXJlciIsImNsaWVudF9pZCI6IkM0ODdkODY5ZDE5ODZmZDY0NWE0OTYzNjVhMTU4NWY2NjkwYjY3YmZjYjJmNTcwN2NiYjgzYTI3M2E3NWQ4ZGI0IiwidXNlcl90eXBlIjoibWFjaGluZSIsInRva2VuX2lkIjoiQWFaM3IwTURZeU5ESmxZalV0T0ROaFppMDBNRFV3TFRsa1pEUXROMkppT1RGbFpqZ3pOVGN4WmpVMVpHTXhNamd0TWpFeSIsInVzZXJfaW5mbyI6InsgXCJkZXZpY2VJZGVudGlmaWVyXCI6IFwiNTQ1ODgzNzctZTI4OS01ZDcwLThlZDUtNjQ3YjU3ZjIyYzVmXCIgfSIsInVzZXJfbW9kaWZ5X3RpbWVzdGFtcCI6IjIwMjUwMzA1MTUxODM4LjIyN1oiLCJyZWFsbSI6ImVmNzBmYWU2LWIwNzktNDVlNi05MDFlLTBhMWJhOTg1NjcyMSIsImNpc191dWlkIjoiYTgxODg2ZjctZGQ0YS00OTliLWFkYzQtNjk3MTdjNjk2Y2Q4IiwiZXhwaXJ5X3RpbWUiOjE3NDEzMjAxMzU0ODl9.i8yKdw7SrNnqYLvR1kxDact2BjoZLYpld5zHSHEdzvhjXs5B6tkUz0BwcpKHh8J34MxpbLkFS6Cl1O20exc-JYAR_fFsUvmqjkMyNX0xQ_Vm9p10LMn9mAiOMj11x7Ok-mSwqFyN1DZjPUWH0RVW0e3q2nlOY267hLysaHAHWQBAAl5fh6j8QfQ9k8E4EY1Z-QgK58bjb0Fx1KybLw9T3n-25QgFsdYKmatj8315W1nFqSp1KOgOjNk_5xoLzzWUyzOqEMslwLHBstpQ9ZfjzzFyMXrUPV4KtHl4xgEwtuFoHEgzpNwf9oceVZZrugI4TcvqDBVLGLutBQkuBWmVng"; // REQUIRED
