// This URL below can be replaced with any Virtual Background Image URL
export const vbgImageUrl = "./images/V_B_G.jpg";

// Obtain the following meetingInfo by creating a new meeting in the Webex Developer Portal
// Read through this API Reference to know more:
// https://developer.webex.com/docs/api/v1/meetings/create-a-meeting
// Once meeting is created, copy the whole response and paste it here.
// Note - Unless we have this information, this demo cannot join a meeting
export const meetingInfo = {}; // REQUIRED

// To get guestIssueAccessToken and guestEndpointUrl
// Update the following with the Guest Issuer Access Token through Service Apps
// Read more about it here: https://developer.webex.com/docs/sa-guest-management
// Note - Unless we have this token, this demo cannot join a meeting
export const guestIssuerAccessToken = ""; // OPTIONAL
export const guestEndpointUrl = ""; //OPTIONAL

//To get access token visit - https://developer.webex.com/docs/getting-started
export const personalAccessToken = "eyJhbGciOiJSUzI1NiJ9.eyJtYWNoaW5lX3R5cGUiOiJseXJhX3NwYWNlIiwiY2x1c3RlciI6IlAwQTEiLCJwcml2YXRlIjoiZXlKamRIa2lPaUpLVjFRaUxDSmxibU1pT2lKQk1USTRRMEpETFVoVE1qVTJJaXdpWVd4bklqb2laR2x5SW4wLi4wbEJwTGQ4Y2YzT0NyNFdxTnhwN2xBLnhpSHpHT1BRMWFrYkRYVzQ3Wnh6Yl9LNmVDZVo0aU5ibC1wdFNWY2tHM2owRE5xUERTSWFwS2JwUHRVQ0ttb2pudk5SYTVGTmsyZXpXbDBLY3p6bG91U21SZ25KaE1WYVgxX1RhVGRKMWZLbzhURmFhal9Kd3BncG9BVFN4dEZpUjU1aE9ydzNtcF95MXNqR1h1NVM3R3MzbHhSN2xNM1FQMHNQSGU5SDZfTUljUWJWanI2NXdEQ282QlpNWUFFRFdnYWViT2twQnZ0cTMtWmZKSF9fbTRERGJUWnhiSlRzQWwxa0wtRTRieThZaGZ2eUk1aS1LYWhINlBNTFhaaF8wRjdXWTlWLXFlUDh0MGU2YUhYbmh3X1MtbU9iUjExbXN3Vjl0NnhNbTYzLWpNTzRvU01ZRTF2ZlVOMTRkdU01bzlSd1d1U3JMNWVpN2hmSUJ1VjM1MUQ1RldpQkdIemxUczR5RHVDTlNMUFE3YXBaN052V1ZQdHlpMTdlNUFYU0RHRmRjdTJJNzFBcGFjNHRIOVpJWG1Yc2tybG5NS3hibjhYUHl5WXlvRE9sOHBNcm1fRW84cDRFYmRaakxuSS1RejF5LUh2U2tnV3VSSXhWS053NUd4VVltR3pwVmMydFdqbXRBVWdQNTlXUExiYmxnTFM4dFd1VWQzZmxYUnVCeXBhenhxRDQyeGRyWG9KUXk0dzhsR0NkWUJQR3duQURQZVVmRjRDd1FZaGRMOXBBbkRhX2tMTUlXRm53X3pKWkh6M0NMWlhpSkVhTUstT3g2N045aklyaVh3RzhzaGg2bjhSdWFnWmtXSU41T2RxNmxHUWlzaVNGbGMtZV8yb2tNMnNZem9VZUR1aVVBMGxjcG1oUlQ1R19EM21XU3REWFlpd3A4cHp6eXlVLlk2NUtYUHJfU2ExaUFyWFctM2dGclEiLCJyZWZlcmVuY2VfaWQiOiI1NDVmYWQxYS0xNGY4LTQ4Y2ItYWEzYy0wYzRlYzZhOGMzYjciLCJpc3MiOiJodHRwczovL2lkYnJva2VyLWItdXMud2ViZXguY29tL2lkYiIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJjbGllbnRfaWQiOiJDNDg3ZDg2OWQxOTg2ZmQ2NDVhNDk2MzY1YTE1ODVmNjY5MGI2N2JmY2IyZjU3MDdjYmI4M2EyNzNhNzVkOGRiNCIsInVzZXJfdHlwZSI6Im1hY2hpbmUiLCJ0b2tlbl9pZCI6IkFhWjNyME1EaGlNVGcyT1dJdE9ERm1aaTAwTnpFMkxXSTFaR010WWpoak1UY3hOek0yTVdFME56WmhOekl5WWpjdFpERTEiLCJ1c2VyX2luZm8iOiJ7IFwiZGV2aWNlSWRlbnRpZmllclwiOiBcIjU0NTg4Mzc3LWUyODktNWQ3MC04ZWQ1LTY0N2I1N2YyMmM1ZlwiIH0iLCJ1c2VyX21vZGlmeV90aW1lc3RhbXAiOiIyMDI1MDEyMTA0MjgxOS43NDlaIiwicmVhbG0iOiI2MmZkOGVmNi02YTFhLTQ5OTUtOTdiZS1kYTA5ZmQzYTdhODUiLCJjaXNfdXVpZCI6ImViMmQ1YTY3LTFmZmQtNGY5OS05ZGRjLWNkYmU4YzdkZjcyMiIsImV4cGlyeV90aW1lIjoxNzM4Mjc1NDU4OTc2fQ.eJjhxJr2fump18opeThQVt3DOp-KeS8lma7AGAmlVzTDwi-qJ4pW0ls_pVvVgj8ARnqpAbRXgSoeKOPV9cQTKDGTjE22YQnsylBEZgT2kZ-Vy03YUYutobe6hNyn81RcPO3qvOdecGwTkdCCswMExMQ_49ET4YVGldp-82mXWxqePlZ1zPfOWr9TBQYtmeunNMp81dm0KblvM-bhKLOY4gyGOtw1gPQ_bA4Puduq6YcWCMAljtmecSfrWALcb8ZzMlyRg9zKEOVCMZ-bUZyc_qwNwdUehW130iEfFIvnxiRfnHOwrt4v4DbhPrlJPEyePmWsZSdH3FpEaEMsfiuJYA"; // REQUIRED
